### PR TITLE
:sparkles: Allow customize proposal url

### PR DESCRIPTION
**Pull request by msfernandes**
Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>

### CODE REVIEW

**Comment by msfernandes** [comment]
@caepenna To review this PR just enter on admin page and try to add a custom url to any proposal. To do this you must check `custom url` checkbox. If you leave it unchecked the system will fill the field with the default url: `http://www.camara.gov.br/proposicoesWeb/fichadetramitacao?idProposicao=<id>`

obs: The Câmara webservice is currently unstable, you may find errors when try to get the default url

**Comment by caepenna** [comment]
@msfernandes I wasn't able to test it, when try to access a proposal to change its URL i got this error
screen shot 2017-09-08 at 15 11 30

**Comment by msfernandes** [comment]
Sorry... Run `./manage.py migrate` before :)

**Review by caepenna — APPROVED** [review]
😎

**Pull request merged**
